apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::155462959201:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1C9BWD38PNHTX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::155462959201:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-03T14:57:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "236509"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 90d7d9e1-f9ca-4e89-8606-06efe1c8ba5d
